### ISSUE TITLE
백엔드의 HOST를 환경변수로 지정할 수 있게 해주세요

### ISSUE THREAD

**Issue by hepheir** [tle-ko/fe-web-react#185]
현재 [/src/utils.js](https://github.com/tle-ko/fe-web-react/blob/1cbb2e60f723a448dc1d69f1dda877ad68ea2d2c/src/utils.js#L10)에서

```javascript
export const client = axios.create({
  withCredentials: true,
  baseURL: process.env.REACT_APP_API_BASE_URL,
  headers: {
    'Content-Type': process.env.REACT_APP_CONTENT_TYPE,
  },
});
```

위의 코드에 `process.env.REACT_APP_API_BASE_URL`가 그 역할인 것으로 알고있는데, 브라우저에서는 이것이 잘 적용되지 않는 것으로 보입니다.

**Comment by Whatdoyumin** [comment]
각 api 요청의 불필요한 path를 제거했으니 확인 부탁드립니다.

**Comment by hepheir** [comment]
아직 고쳐지지 않았습니다.

아래와 같이`signupForm.jsx:57`에서 에러가 발생하네요

<img width="1912" alt="Screenshot 2024-11-17 at 03 00 24" src="https://github.com/user-attachments/assets/c79e6997-2d05-4b1a-8ac5-f90b73ed12e3">
