### ISSUE TITLE
리액트 development build 에서 production build로 바꾸어주세요

### ISSUE THREAD

**Issue by hepheir** [tle-ko/fe-web-react#188]
![image](https://github.com/user-attachments/assets/8bcf4a8f-7b49-4a58-916f-1ca428f0471e)

개발 버전으로 배포할 경우, 성능 저하 및 보안의 위험이 있습니다.

**Comment by ohcuy** [comment]
#187 
웹소켓 문제도 겸사겸사 해결했습니다 ㅎㅎ
![IMG_7391](https://github.com/user-attachments/assets/a515edd0-c42c-434f-92d9-14c60e0a2888)
